### ISSUE TITLE
SWIFT Compiler Error: 'Material' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by mmolero** [john-rocky/RealityKitSampler#2]
First it all, Thanks for sharing, the project from the readme it looks a very nice resource to learn about Reality Kit
I have cloned your repo however, when I tried to compile it, I got the the following issue:

`'Material' is ambiguous for type lookup in this context`

Do you know why it happens?, 
Thanks!!

**Comment by john-rocky** [comment]
Hi mmolero.

I fixed those errors.
Now, you can build this project.Please pull new one.

It has happened on importing SwiftUI(no needed) and RealityKit. System did not know "Material" is which one's.
And I fixed libraries compile errors.

Thank you for telling me about these bugs.
If you have some problem again, please tell me any time.

Daisuke

**Comment by mmolero** [comment]
Now it works 
I will let you know if I find more issues 
Thanks!!!
